# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/php
image: lorisleiva/laravel-docker:8.0

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: project_name
  MYSQL_ROOT_PASSWORD: secret

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - vendor/
    - node_modules/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  # Install Composer and project dependencies.
  - composer install

  # Install Node dependencies.
  # comment this out if you don't have a node dependency
  - npm install

  # Run npm build
  # comment this out if you don't have a frontend build
  # you can change this to do your frontend building script like
  # npm run build
  - npm run dev
  - npm run production

format:
  script:
    - php vendor/bin/php-cs-fixer fix --config .php-cs-fixer.php --allow-risky=yes | grep 1\) && exit 1 || exit 0
    - php vendor/bin/psalm

test:
  script:
    - XDEBUG_MODE=coverage php vendor/bin/phpunit --coverage-text --colors=never
    - php coverage-checker.php build/clover.xml 80
